// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTcHcaFwSPBVHhVIeKAh_4tbM4ptlQh_4',
    appId: '1:295020449832:web:c909b73cd63a0cba35651d',
    messagingSenderId: '295020449832',
    projectId: 'movietestapp-9caad',
    authDomain: 'movietestapp-9caad.firebaseapp.com',
    storageBucket: 'movietestapp-9caad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe1cvRbU74-u0i4hIxUxYxX-34FcAsxE0',
    appId: '1:295020449832:android:3bd8f422147bd63e35651d',
    messagingSenderId: '295020449832',
    projectId: 'movietestapp-9caad',
    storageBucket: 'movietestapp-9caad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZuTWs_X87_tAg6eYL8eLtXwaxjXrMeBU',
    appId: '1:295020449832:ios:ca00604b5cb6b39935651d',
    messagingSenderId: '295020449832',
    projectId: 'movietestapp-9caad',
    storageBucket: 'movietestapp-9caad.appspot.com',
    iosBundleId: 'com.example.movietestapp',
  );
}
